sudo: required
language: python

services:
  - docker

cache:
   directories:
   - "$HOME/google-cloud-sdk/"

script:
  - bin/build-docker.sh -p
  - bin/test.sh -p

after_success:
  - bin/deploy-gcloud.sh