services:
  - docker

# addons:
#   apt:
#     sources:
#       - "ubuntu-toolchain-r-test"
#     packages:
#       - "g++-4.8"
# cache:
#   apt: true

script:
  - bin/build-docker.sh -p
  - bin/test.sh -p
  - bin/deploy.sh