services:
  - docker

cache:
   directories:
   - "$HOME/google-cloud-sdk/"

install:
  - bin/install-gcloud-sdk.sh

script:
  - bin/build-docker.sh -p
  - bin/test.sh -p

after_success:
  - bin/deploy.sh