services:
  - docker

install:
  - bin/install-gcloud-sdk.sh
  - bin/install-kubectl.sh

script:
  - bin/authenticate-gcloud.sh
  - bin/build-docker.sh -p
  #- bin/test.sh -p

after_success:
  - bin/deploy.sh