sudo: required

language: python
python:
  - "3.7"

services:
  - docker

#install:
#  - pip install --upgrade awscli

script:
  - bin/build-docker.sh -d
  #- bin/test.sh -p

after_success:
  - bin/start-docker.sh -d
