version: '3.4' 
services:

  wobbly-backend-service:
    build:
      context: .
      dockerfile: DOCKERFILE.development
    image: $DOCKER_IMAGE
    command: bash bin/docker-entrypoint-development.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=wobbly-backend-db
      - POSTGRES_PORT=5432    
    depends_on:
      - wobbly-backend-db   

  wobbly-backend-db:
    image: postgres
    ports:
      - "5432:5432"