FROM nginx:1.14.0
EXPOSE 80

RUN rm /etc/nginx/conf.d/default.conf
#COPY /var/www/html /usr/share/nginx/html
#COPY conf /etc/nginx
#COPY wobbly.app.nginx.conf /etc/nginx/conf.d/default.conf
#RUN service nginx restart

RUN nginx -T