version: '3.6'
services:

  wobbly-backend-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: $DOCKER_IMAGE
    command: bash bin/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD