version: '3.4' 
services:
  wobbly-backend-db:
    image: postgres
    ports:
      - "5432:5432"

  wobbly-backend-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: $DOCKER_IMAGE
    command: bin/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - wobbly-backend-db
    environment:
      - DJANGO_SECRET_KEY
      - DEBUG
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=wobbly-backend-db
      - POSTGRES_PORT=5432