version: '3.4' 
services:

  wobbly-app-backend-service:
    image: $DOCKER_IMAGE:latest
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=wobbly-app-backend-db
      - POSTGRES_PORT=5432 
      - DEBUG=True  
    depends_on:
      - wobbly-app-backend-db

  wobbly-app-backend-db:
    image: postgres:9.6.10
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pw

  wobbly-app-nginx:
    image: wobbly-app-backend-nginx
    build:
      context: .
      dockerfile: DOCKERFILE.nginx
    ports:
      - "80:80"
    depends_on:
      - wobbly-app-backend-service